var wordsModule = (function(){
    var words = [
        "Gotham's new district attorney has been elected. His name is Harvey Dent, and he has a radical new agenda that threatens to take down Gotham's organized crime underworld once and for all with an iron fist.| But the emergence of the rogue vigilante known as Batman has caused problems for Dent and his agenda. A new criminal mastermind known only as The JOKER has arrived and aims to take Gotham out from under Harvey Dent's iron fist.| The Joker stages a masterfully planned bank robbery and robs the Gotham mob blind. He uses this money to stage a series of horrific and strategic attacks against the city and its people - each one carefully planned and aimed at Dent and Batman while causing the rest of the city to enter panic mode.| Meanwhile, Batman thinks he might have found a lead to The Joker thanks to Wayne Enterprises' dealings with a shady Chinese banker, and that takes Batman and Alfred to Hong Kong. The Joker has no rules, but Batman has only one, and the Joker aims to make Batman break his only rule. But who will be the one to take him out - will it be rogue vigilante Batman or will it be elected official Harvey Dent, the new hero with a face?",
        
        "Nine noble families fight for control of the mythical land of Westeros. Political and sexual intrigue is pervasive. Robert Baratheon, King of Westeros, asks his old friend Eddard, Lord Stark, to serve as Hand of the King, or highest official.| Secretly warned that the previous Hand was assassinated, Eddard accepts in order of business to investigate further. Meanwhile the Queen's family, the Lannisters, may be hatching a plot to take power.| Across the sea, the last members of the previous and deposed ruling family, the Targaryens, are also scheming to regain the throne. The friction between the houses Stark, Lannister, Baratheon and Targaryen and with the remaining great houses Greyjoy, Tully, Arryn, Tyrell and Martell leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war and political confusion, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
		
		"Harry Potter thinks he is an ordinary boy celebrating his 11th birthday, but he is far from right. A giant named Hagrid appears, and gives Harry the all important news. He is a wizard.| Now his journey in life gets more intense as he travels to Hogwarts school of witchcraft and wizardry to learn the trade of being a wizard. Here, he meets his friends who would be by his side for many years to come.| Ron Weasley is not very brave friend and Hermione is the smart friend. But not everything is quiet at Hogwarts as Harry suspects someone is planning to steal the sorcerer's stone."
    ];

    return{
        getWords(textNumber){
            return words[textNumber];
        }
    }
})();